Feat/login component
projeto-dev404/juliett-squad pull request #6
Opened 2023-10-03 23:35 UTC by gabrielmoisesa

Criação do componente de login com o header, contendo a logo da CodeMentor e o nome "CodeMentor" embaixo. Além de adicionar flex no app.

### Checklist

- [ ] Adicionou testes?
- [ ] Testou em telas menores? `NA`
- [ ] Colocou `assignee` no PR?
- [ ] Colocou `label` no PR?

2023-10-04 12:17 UTC, davidsonmarra commented
Gabriel, como o seu PR é o primeiro ele definirá a estrutura e o padrão a ser seguido dentro do app. Então, recomendo alguns pontos de refactor:
- Criar uma pasta `src` e colocar todos os componentes que você criar lá dentro
- O nome dos arquivos é um padrão a ser combinado, mas eu gosto de tudo minúsculo separado por `-`, ou seja, algo como: `login-page`. O que acha?
- Crie o componente `Header` dentro de uma pasta `components` dentro da `src`

Por enquanto, coisas geral é isso. Vou fazer alguns comentários em partes específicas.

2023-10-04 12:31 UTC, davidsonmarra commented on LoginPage/Header.tsx
> +const logoImage: ImageURISource = codeMentorLogo as ImageURISource;
Essa forma de usar imagens funciona, a tipagem funciona bem porém você escreve de mais. 
Procure outras formas de tipar imagens de maneira "global" e usá-las mais diretamente.

2023-10-04 12:49 UTC, davidsonmarra commented on LoginPage/Login.tsx
> +    flex: 2,
Flex 2 não faz sentido. Acredito que seja flex:1 aqui. Dê uma pesquisada sobre o funcionamento.

2023-10-04 12:51 UTC, davidsonmarra requested changes
Resolver os comentários.

2023-10-05 03:59 UTC, gabrielmoisesa commented
> Gabriel, como o seu PR é o primeiro ele definirá a estrutura e o padrão a ser seguido dentro do app. Então, recomendo alguns pontos de refactor:
> 
> * Criar uma pasta `src` e colocar todos os componentes que você criar lá dentro
> * O nome dos arquivos é um padrão a ser combinado, mas eu gosto de tudo minúsculo separado por `-`, ou seja, algo como: `login-page`. O que acha?
> * Crie o componente `Header` dentro de uma pasta `components` dentro da `src`
> 
> Por enquanto, coisas geral é isso. Vou fazer alguns comentários em partes específicas.

Comentários resolvidos! 
Só fiquei em dúvida sobre uma questão. Na questão de nomeamento de arquivos, você recomendou a utilização do kebab-case, mas no próximo comment, utilizou Pascal para o componente Header, a dúvida seria então para quais tipos de arquivos? Pastas? Todos? Como na dúvida, deixei o LoginPage como Pascal igual ao Header, ok?

2023-10-05 12:18 UTC, davidsonmarra commented
Seguinte, só coloquei o Header como pascal pra referenciar seu componente. Pode criar tudo como kebab mesmo.

2023-10-31 14:16 UTC, davidsonmarra approved these changes

2023-10-31 19:29 UTC, merged